### ISSUE TITLE
orangetext

### ISSUE THREAD

**Issue by untuned** [ssterling/bukkitgreentext#1]
suggestion to add orangetext
![orangetext](https://i.untuned.me/CGxGl3.png)

**Comment by ssterling** [comment]
oof I just now remembered I had a GitHub (primarily use [GitLab](https://gitlab.com/ssterling/bukkitgreentext)), sorry about that

but honestly I'm down; I'll probably have a v1.1 with orange out sometime tomorrow at 15:00 EDT

![implying](https://i.redditmedia.com/i2NxrKvs1nrsIXYflP7qU8ONLbeXoiAYAdRXz6q8S3A.png?w=396&s=af64e1818aacf21c1f8542e708661ecd)

**Comment by ssterling** [comment]
Done!  See tag for [version 1.1](https://github.com/ssterling/bukkitgreentext/releases/tag/1.1)
